"""Generate the service reference from the public registry JSON."""

import argparse
import json
from pathlib import Path


def render(registry):
    lines = [
        "# Service registry reference",
        "",
        "Generated by `scripts/generate-service-docs.py`; edit registry metadata to change this table.",
        "",
        "This table describes configuration. Runtime coverage is recorded in [the support matrix](../support-matrix.md).",
        "",
        "| ID | Display name | Public option | Port | Backup directory | Exporter | Presets | Coverage / selection guidance | Requirements |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for key, entry in sorted(registry.items()):
        option = "nixstead.services." + ".".join(entry["optionPath"])
        backup = entry.get("backup") or {}
        metrics = entry.get("metrics") or {}
        setup = entry.get("setup") or {}
        values = [
            key,
            entry["name"],
            option,
            str(entry["defaults"].get("port", "—")),
            backup.get("directory", "—"),
            metrics.get("exporter", "—"),
            ", ".join(setup.get("presets", [])) or "—",
            setup.get("support", "Evaluation only; see support matrix"),
            setup.get("requirements", "See service guide"),
        ]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("registry", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render(json.loads(args.registry.read_text()))
    if args.check:
        if not args.destination.exists() or args.destination.read_text() != content:
            raise SystemExit(
                "Service documentation drift: regenerate docs/generated/services.md"
            )
    else:
        args.destination.parent.mkdir(parents=True, exist_ok=True)
        args.destination.write_text(content)


if __name__ == "__main__":
    main()
