"""Recreate a missing native Seafile SQL account from its private configuration."""

import configparser
from pathlib import Path
import subprocess
import sys
import time


def quote(value):
    return "'" + value.replace("'", "''") + "'"


def main():
    path = Path(sys.argv[1])
    if not path.exists():
        return
    config = configparser.ConfigParser(interpolation=None)
    config.read(path)
    user = config["database"]["user"]
    password = config["database"]["password"]
    if not user or not password or user == "root":
        raise ValueError("Unsupported application account")
    command = [
        sys.argv[2],
        "exec",
        "-i",
        "seafile-db",
        "sh",
        "-c",
        'export MYSQL_PWD="${MARIADB_ROOT_PASSWORD:-$MYSQL_ROOT_PASSWORD}"; '
        "exec mariadb --protocol=tcp --host=127.0.0.1 --user=root --batch",
    ]
    deadline = time.monotonic() + 120
    while time.monotonic() < deadline:
        try:
            result = subprocess.run(
                command,
                input=b"SELECT 1;",
                capture_output=True,
                timeout=min(5, max(0.1, deadline - time.monotonic())),
            )
        except subprocess.TimeoutExpired:
            continue
        if result.returncode == 0:
            break
        time.sleep(1)
    else:
        raise RuntimeError("Database readiness failed")
    # Match the host selector generated by the pinned native bootstrap. The
    # IF NOT EXISTS form preserves an already configured account's password.
    account = quote(user) + "@'%.%.%.%'"
    statements = [
        "SET SESSION sql_mode='NO_BACKSLASH_ESCAPES';",
        "CREATE USER IF NOT EXISTS "
        + account
        + " IDENTIFIED BY "
        + quote(password)
        + ";",
    ]
    statements.extend(
        "GRANT ALL PRIVILEGES ON `" + name + "`.* TO " + account + ";"
        for name in ("ccnet_db", "seafile_db", "seahub_db")
    )
    result = subprocess.run(
        command, input="\n".join(statements).encode(), capture_output=True, timeout=30
    )
    if result.returncode != 0:
        raise RuntimeError("Application account provisioning failed")


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # Driver/SQL diagnostics can contain secrets read from native conf.
        print(
            "Seafile database account provisioning failed; application not started.",
            file=sys.stderr,
        )
        raise SystemExit(1) from None
